version: "3"
services:
  petcare_app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://localhost:3307/petcare?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER: root
      DB_PASSWORD: 1234
    restart: always
    depends_on:
      db_petcare:
        condition: service_healthy

  db_petcare:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: petcare
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping","-h", "localhost"]
      timeout: 10s
      retries: 10