spring:
  aplilcation:
    name: petcare
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: ${JWT_SECRET:123456}
  expiration-ms: 10800000

security:
  public-routes: /api/v1/auth,/api/v1/user/register
